### POST REGISTER USER
POST http://localhost:3000/api/users/register HTTP/1.1

{    
   "name": "Name",
   "lastname": "Lastname",
   "email":"Email",
   "pass":"Password"
}

### POST LOGIN USER
POST http://localhost:3000/api/users/login HTTP/1.1

{    
   "email":"Email",
   "pass":"Password"
}

### GET CONFIRM USER
GET http://localhost:3000/api/users/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkVtYWlsIiwiaWF0IjoxNjg1MjgyMjM5LCJleHAiOjE2ODUzNjg2Mzl9.x2WxzR-xcr2Wx2hVoHvkhV8mLgbYQP7oCjMmijkTxkY HTTP/1.1

### GET ALL USERS
GET http://localhost:3000/api/users HTTP/1.1