### GET metadata
GET http://localhost:3000/api/filters/metadata/1681890129922 HTTP/1.1

### PATCH filters
PATCH  http://localhost:3000/api/filters HTTP/1.1
content-type: application/json

{
  "id": 1681890129922,
  "action": "crop",
  "filters": {
      "rotate": 90,
      "resize": {"width": 200, "height": 120},
      "toFormat": "png",
      "crop": { "width": 200, "height": 200, "left": 20, "top": 20 },
      "tint": {"r":255,"g":255,"b":0}
  }
}